export interface IMapSetting {
  id: number;
  branch_id: number;
  branch_name_ar?: string | null;
  branch_name_en: string;
  customer_account_id: number;
  customer_account_name_ar?: string;
  customer_account_name_en: string;
  vendor_account_id: number;
  vendor_account_name_ar?: string | null;
  vendor_account_name_en: string;
  employee_account_id: number;
  employee_account_name_ar?: string | null;
  employee_account_name_en: string;
  payroll_expense_id: number;
  payroll_expense_name_ar?: string | null;
  payroll_expense_name_en: string;
  issue_cheque_account_id: number;
  issue_cheque_account_name_ar?: string | null;
  issue_cheque_account_name_en: string;
  recival_cheque_account_id: number;
  recival_cheque_account_name_ar?: string | null;
  recival_cheque_account_name_en: string;
  opening_balance_id: number;
  opening_balance_name_ar?: string | null;
  opening_balance_name_en: string | null;
  inventory_account_id: number;
  inventory_account_name_ar?: string | null;
  inventory_account_name_en: number; 
  sale_account_id: number;
  sale_account_name_ar?: string | null;
  sale_account_name_en: string;
  purchase_account_id: number;
  purchase_account_name_ar?: string | null;
  purchase_account_name_en: string;
  sale_return_account_id: number;
  sale_return_account_name_ar?: string | null;
  sale_return_account_name_en: string;
  purchase_return_account_id: number;
  purchase_return_account_name_ar?: string | null;
  purchase_return_account_name_en: string;
  allowed_discount_id: number;
  allowed_discount_name_ar?: string | null;
  allowed_discount_name_en: string;
  gained_discount_id: number;
  gained_discount_name_ar?: string | null;
  gained_discount_name_en: string;
  vat_input_id: number;
  vat_input_name_ar?: string | null;
  vat_input_name_en: string;
  vat_output_id: number;
  vat_output_name_ar?: string | null;
  vat_output_name_en: string;
  comission_account_id: number;
  comission_account_name_ar?: string | null;
  comission_account_name_en: string;
} //store -show in table..... result of store

export interface MapSettingForm {
  organization_id: number | null | undefined;
  branch_id: number | null | undefined;
  customer: number | null | undefined;
  vendor: number | null | undefined;
  employee: number | null | undefined;
  payroll_expenses: number | null | undefined;
  issue_cheque_portfolio: number | null | undefined;
  recival_cheque_portfolio: number | null | undefined;
  opening_balance: number | null | undefined;
  inventory: number | null | undefined;
  sale: number | null | undefined;
  purchase: number | null | undefined;
  sale_return: number | null | undefined;
  purchase_return: number | null | undefined;
  allowed_discount: number | null | undefined;
  gained_discount:number | null | undefined;
  vat_input: number | null | undefined;
  vat_output: number | null | undefined;
  comission: number | null | undefined;
} //body in submit
export interface MapSettingUpdateForm {
  id?: number | null;
  data?: MapSettingForm;
} //update
