export interface ITransaction {
    id: number,
    record_date: string,
    record_type: string,
    ref_no: string,
    document_number: string | null,
    contact_info: string | null,
    contact_full_name_ar: string | null,
    contact_full_name_en: string | null,
    project_id: number | null,
    project_name_en: string | null,
    project_name_ar: string | null,
    debit: string,
    credit: string,
    jv_number: string,
    notes: string,
    description: string | null,
    created_by: number,
    created_by_en: string,
    created_by_ar: string,
  }